### PR TITLE
fix(#104): fix testSubscribe4

### LINKED ISSUE #104: re-enable testSubscribe4 test
## Summary

- This test case depends on `redis-server`. However, in CI, `redis-server` doesn't exist in `PATH`.
- I don't want to complicate testing in a local environment.

## Related PRs
- #103
- #92

### PR DESCRIPTION
**Pull request by tumile**
Closes #104.

EOF is thrown when a recently closed connection allows message to pass through but response coming back is EOF. I'm not sure why `ConnectionRefused` or `ConnectionReset` is not thrown before the message is sent, but this patch adds check for EOFError to performs necessary reconnect attempt and eventually set `_isConnected = false`.

### CODE REVIEW

File: errors.ts [hunk 1]
```diff
@@ -1,3 +1,5 @@
+export class EOFError extends Error {}
```
Comment (uki00a) [inline errors.ts:1]: :+1:

**Comment by uki00a** [comment]
LGTM, thanks @tumile!
